### PR TITLE
Try to improve the AutoFreeSpace plugin in various ways (Fix #236)

### LINKED ISSUE #236: drftpd deleted a section folder
# Describe the bug
Not sure what caused it, but this is what I saw:

* PRE folder being used earlier the same day
* PRE folder missing later the same day, this was in the logs of master:
```
# PRE folder was last used
INFO 2021-07-05T16:55:50,891 [FtpConn thread 4507886 from <iphidden> - pool-3282540-thread-1]
org.drftpd.master.vfs.VirtualFileSystemInode [] - rename(
  Directory[path=/PRE/GRP/REL]
  [user,group=drftpd,drftpd][creationTime=1625504150826]
  [lastModified=1625504150826][size=1234567]),
  (Directory[path=/A-SECTION/REL][user,group=drftpd,drftpd]
  [creationTime=1625504150826]
  [lastModified=1625504150826][size=1234567])

# Being deleted by the drftpd account, triggerd by a unknown internal call
INFO 2021-07-05T17:16:28,643 [FtpConn thread 4479493 from <iphidden> - pool-3289623-thread-1]
org.drftpd.master.vfs.VirtualFileSystemInode [] -  delete(
  Directory[path=/PRE][user,group=drftpd,drftpd]
  [creationTime=1602370618590]
  [lastModified=1624787464373]
  [size=72632537005])
```

* I ran `site reload` and the folder was created again
```
INFO 2021-07-05T20:30:07,947 [FtpConn thread 4562712 from <iphidden> - pool-3334914-thread-1]
org.drftpd.master.vfs.VirtualFileSystemInode [] - createDirectory(
  Directory[path=/PRE]
  [user,group=drftpd,drftpd]
  [creationTime=1625517007947]
  [lastModified=1625517007947]
  [size=0])
```

# Timeline
* 16:38:18 Autofree started to delete things
* 16:38:20 Autofree stopped deleting things
* 17:16:08 is the last previos VFS operation (incomplete-link deletion)
* 17:16:44 org.drftpd.find.master.Find Index contained an unexistent inode    <- on only NUKED releases
* 20:30:07 I run `site reload` which creates the /PRE folder again (defined in sections.conf)

# Plugins
* Mirror unconfigured
* Autofree enabled in space mode

---
I can really only suspect AutoFree here, but the actions were not logged to master.log or channel, so it can not be confirmed from the  logs. Possibly related to #233 ?
Running code from commit: https://github.com/drftpd-ng/drftpd/commit/f47aa21f3cf13f2851e2a9082fc369ef60d6ab51

### PR DESCRIPTION
**Pull request by mvangoor**
- Add a max iterations per slave config variable to limit the amount of iterations in a single run per slave
- Add more logging and logic to the runs
- MrCleanIt class now has a boolean whether it is already running or not and deny a second run

### CODE REVIEW

File: src/plugins/autofreespace/src/main/java/org/drftpd/autofreespace/master/AutoFreeSpace.java [hunk 1]
```diff
@@ -163,33 +215,40 @@ private void cleanByDate(RemoteSlave remoteSlave) throws SlaveUnavailableExcepti
          */
         private void cleanBySpace(RemoteSlave remoteSlave) throws SlaveUnavailableException {
             long freespace = remoteSlave.getSlaveStatus().getDiskSpaceAvailable();
-            long freespaceSaved = freespace;
+            long freespaceMinimum = AutoFreeSpaceSettings.getSettings().getMinFreeSpace();
 
-            if (freespace >= AutoFreeSpaceSettings.getSettings().getMinFreeSpace()) {
+            if (freespace > freespaceMinimum) {
                 logger.debug("AUTODELETE: Space over limit for slave {} will not clean: {}>={}", remoteSlave.getName(), Bytes.formatBytes(freespace), Bytes.formatBytes(AutoFreeSpaceSettings.getSettings().getMinFreeSpace()));
```
Comment (hrxcodes) [inline src/plugins/autofreespace/src/main/java/org/drftpd/autofreespace/master/AutoFreeSpace.java:221]:
```suggestion
                logger.debug("AUTODELETE: Space over limit for slave {}, will not clean: {}>={}", remoteSlave.getName(), Bytes.formatBytes(freespace), Bytes.formatBytes(AutoFreeSpaceSettings.getSettings().getMinFreeSpace()));
```

File: src/plugins/autofreespace/src/main/java/org/drftpd/autofreespace/master/AutoFreeSpace.java [hunk 2]
```diff
@@ -163,33 +215,40 @@ private void cleanByDate(RemoteSlave remoteSlave) throws SlaveUnavailableExcepti
...
                 return;
             }
 
-            logger.debug("AUTODELETE: Space under limit for {}, will clean: {}<{}", remoteSlave.getName(), Bytes.formatBytes(freespace), Bytes.formatBytes(AutoFreeSpaceSettings.getSettings().getMinFreeSpace()));
+            logger.info("AUTODELETE: Space under limit for {}, will clean: {}<{}", remoteSlave.getName(), Bytes.formatBytes(freespace), Bytes.formatBytes(AutoFreeSpaceSettings.getSettings().getMinFreeSpace()));
```
Comment (hrxcodes) [inline src/plugins/autofreespace/src/main/java/org/drftpd/autofreespace/master/AutoFreeSpace.java:225]:
```suggestion
            logger.info("AUTODELETE: Space under limit for slave {}, will clean: {}<{}", remoteSlave.getName(), Bytes.formatBytes(freespace), Bytes.formatBytes(AutoFreeSpaceSettings.getSettings().getMinFreeSpace()));
```

**Review by hrxcodes — COMMENTED** [review]
Streamline the log message, but code seems to work as intended and hopefully will adress the open issue.

`Skipping section [PRE] as no configuration exists`
Closes: #236

**Review by hrxcodes — APPROVED** [review]
Looks good on my end, thanks
